### ISSUE TITLE
Error with make build

### ISSUE THREAD

**Issue by ksteverson** [aica-iwg/aica-agent#34]
I've hit an error when attempting to do the "MODE=emu make build" command. The output I get is:

flower
xargs: venv/bin/safety: exited with status 255; aborting
make: *** [Makefile:37: security] Error 124

I've double checked, and I believe I've installed all the dependencies listed in the setup instructions. My OS environment is Ubuntu 20.04.4 LTS. I am using the current version of the repo as of 6/16/2022.

**Comment by bblakely-anl** [comment]
This should now be fixed in the main branch. Thanks again!
